version: '3.9'

services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dental_clinic
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    image: adoptopenjdk:11-jre-hotspot
    volumes:
      - ./dentistry-2.7.0.jar:/app.jar
    command: java -jar app.jar
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dental_clinic
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8086:8086'
    depends_on:
      postgres:
        condition: service_healthy
  client:
    build: ./client/front-end
    container_name: frontend_c
    ports:
      - '80:3000'
    stdin_open: true
    tty: true